[technote]
id = "SITCOMTN-102"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-102.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-102"
github_default_branch = "main"
date_created = 2023-12-12T14:03:04Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"

[technote.status]
state = "stable"

[technote.authors]
name.given = "Nacho"
name.family = "Sevilla"
internal_id = "sevillai"
affiliations = [{name = "CIEMAT", internal_id = "CIEMAT", address = "Av. Complutense 40 28040 Madrid Spain"}]


